name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run Ruff linting
        run: |
          echo "Running Ruff linting with auto-fix..."
          ruff check --fix src/ tests/
          echo "Linting completed"

      - name: Run Ruff formatting
        run: |
          echo "Running Ruff formatting..."
          ruff format src/ tests/
          echo "Formatting completed"

      - name: Verify no linting issues remain
        run: |
          echo "Verifying no linting issues remain..."
          ruff check --output-format=github src/ tests/
          echo "Verification completed successfully"

      - name: Commit formatting changes
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "style: auto-format and lint with Ruff"
            git push
          fi
